export const LOAD_PRODUCTS_PENDING = "LOAD_PRODUCTS_PENDING";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAIL = "LOAD_PRODUCTS_FAIL";
export const TOGGLE_FILTER_BUTTON = "TOGGLE_FILTER_BUTTON";
export const TOGGLE_SEARCH_BUTTON = "TOGGLE_SEARCH_BUTTON";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const FILTER_PRODUCTS_BY_SORTING = "FILTER_PRODUCTS_BY_SORTING";
export const FILTER_PRODUCTS_BY_PRICE_INTERVAL =
  "FILTER_PRODUCTS_BY_PRICE_INTERVAL";
export const FILTER_PRODUCTS_BY_USER_INPUT = "FILTER_PRODUCTS_BY_USER_INPUT";
