const products = [
  {
    productId: "0000001",
    name: "women t-shirt white",
    price: "179 kr",
    type: "women",
    img_url: "product-01.jpg",
  },
  {
    productId: "0000002",
    name: "women shirt white",
    price: "379 kr",
    type: "women",
    img_url: "product-02.jpg",
  },
  {
    productId: "0000003",
    name: "man shirt blue",
    price: "279 kr",
    type: "men",
    img_url: "product-03.jpg",
  },
  {
    productId: "0000004",
    name: "feather coat",
    price: "1489 kr",
    type: "women",
    img_url: "product-04.jpg",
  },
  {
    productId: "0000005",
    name: "denim suit",
    price: "879 kr",
    type: "women",
    img_url: "product-05.jpg",
  },
  {
    productId: "0000006",
    name: "quartz watch with carbon leather",
    price: "2879 kr",
    type: "watch",
    img_url: "product-06.jpg",
  },
  {
    productId: "0000007",
    name: "plaid cote",
    price: "1249 kr",
    type: "women",
    img_url: "product-07.jpg",
  },
  {
    productId: "0000008",
    name: "cactus white t-shirt ",
    price: "149 kr",
    type: "women",
    img_url: "product-08.jpg",
  },
  {
    productId: "0000009",
    name: "black sneakers ",
    price: "679 kr",
    type: "shoes",
    img_url: "product-09.jpg",
  },
  {
    productId: "00000010",
    name: "black tight under shirt ",
    price: "479 kr",
    type: "women",
    img_url: "product-10.jpg",
  },
  {
    productId: "00000011",
    name: "blue plaid shirt ",
    price: "359 kr",
    type: "men",
    img_url: "product-11.jpg",
  },
  {
    productId: "00000012",
    name: "brown leather belt ",
    price: "399 kr",
    type: "men",
    img_url: "product-12.jpg",
  },
  {
    productId: "00000013",
    name: "white under shirt ",
    price: "299 kr",
    type: "women",
    img_url: "product-13.jpg",
  },
  {
    productId: "00000014",
    name: "black under shirt with rose",
    price: "149 kr",
    type: "women",
    img_url: "product-14.jpg",
  },
  {
    productId: "00000015",
    name: "quartz watch with carbon steel",
    price: "1599 kr",
    type: "watch",
    img_url: "product-15.jpg",
  },
  {
    productId: "00000016",
    name: "long sleeve under shirt",
    price: "89 kr",
    type: "women",
    img_url: "product-16.jpg",
  },
];
export default products;
